[plugin]
repository = "https://github.com/PunishedPineapple/WhatDidYouSay.git"
commit = "4f100f92ebaf41f1f71423ce4cc298f35a426f23"
owners = [
    "PunishedPineapple",
]
project_path = "WhatDidYouSay"
changelog = '''
- Updated for Dalamud API 9.
- Minor improvement to settings window.
- Minor code cleanup.
'''